// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Return the appropriate FirebaseOptions based on the target platform
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ${defaultTargetPlatform} - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEWazqr4OjfEiOO4lzu-50MKMJJkuGHtI',
    appId: '1:614587521688:android:b465c30d7102ea3ead0eed',
    messagingSenderId: '614587521688',
    projectId: 'fir-sample-app-4e504',
    storageBucket: 'fir-sample-app-4e504.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEWazqr4OjfEiOO4lzu-50MKMJJkuGHtI',
    appId: '1:614587521688:ios:b465c30d7102ea3ead0eed',
    messagingSenderId: '614587521688',
    projectId: 'fir-sample-app-4e504',
    storageBucket: 'fir-sample-app-4e504.appspot.com',
    iosBundleId: 'com.example.firebase_sample_app',
  );
}
